### PR TITLE
Fix for django 4.x 

### LINKED ISSUE #50: Not working with Django 4.x
Short description explaining the high-level reason for the new issue.

## Current behavior

Not working with Django 4.x

## Expected behavior

To *work* with Django 4.x

## Steps to replicate behavior (include URLs)

1. Run this with Django 4.x

The problem is with the Django 4.x dropping the ugettext and ugettext_lazy aliases.

### PR DESCRIPTION
**Pull request by spapas**
Fixes #50. 

Please merge this and create a new release so we'll be able to use the package with django 4.x

In the meantime use this in your requirements.txt:

`-e git+https://github.com/spapas/wagtail-sharing#egg=wagtail_sharing`

BR,
Serafeim

### CODE REVIEW

**Comment by zerolab** [comment]
@spapas could you add Django 4.0 to tox.ini and a toxenv for it in `.github/workflows/test.yml` ? would help with testsuite

**Comment by spapas** [comment]
> @spapas could you add Django 4.0 to tox.ini and a toxenv for it in `.github/workflows/test.yml` ? would help with testsuite

Hey @zerolab I tried but got the following error while trying to change test.yml:

```
 ! [remote rejected] main -> main (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/test.yml` without `workflow` scope)
```

**Comment by zerolab** [comment]
@spapas you may need to enable github workflows in your fork settings? 🤔
can't say I've seen that before. maybe try https://stackoverflow.com/a/68812023/201316 ?

**Comment by spapas** [comment]
Thanks @zerolab it works after I updated my personal token to allow workflow! 

It was my stupid mistake, usually I clone projects using ssh but for some reason I cloned this project using https and then it used the personal token (that didn't have workflow access)

**Comment by chosak** [comment]
Hi @spapas, thanks for this. It looks to me like the tests for Django 4.0 failed because [we invoke `django-admin.py`](https://github.com/cfpb/wagtail-sharing/blob/839b56ee19ef00b0dfa623b61dbc430c9a4c488a/tox.ini#L12), which [has been deprecated in Django 4.0](https://docs.djangoproject.com/en/4.0/releases/3.1/#id2) in favor of `django-admin`. Would you be able to add that change to this PR?

**Comment by spapas** [comment]
Hello @chosak I'd be happy to however notice that django-admin is an executable (it's actually an .exe file on windows) so it can't be run with `coverage.exe run` (since the run expects a python script). After some research I tried to do it with -m django and it works. 

However now I get a failing test for Django 4.x (the test passes for Django 3.2). I really can't  understand why this test is failing, it seems that the problem is on the line `self.assertEqual(self.urlpatterns[1].callback.__name__, "ServeView")` of test_urls.py: In Django 4.x it returns `view` instead of the expected `ServeView`. I did some research and can't understand why this behavior happens. Notice that I'm using this in my Wagtail 2.16 / Django 4.0.2 project and it works fine.

**Comment by chosak** [comment]
Thanks @spapas! I also did some digging and suspect that test failure is due to the change in https://github.com/django/django/commit/7c08f26bf0439c1ed593b51b51ad847f7e262bc1, which deliberately changes how view function attributes are set.

I've opened #52 as a separate PR because I didn't want to push to your fork; would you be able to give that branch a try? Thanks also for your Windows suggestion - we don't typically test our packages on Windows so it's very helpful that you identified that potential issue with `django-admin`.

**Comment by spapas** [comment]
Hello @chosak I just tested your `feature/django-4.0` and works great on my environment :) I'm closing this in favor of PR #52. 

Thank you so much!

**Pull request closed without merging**
