### PR TITLE
Adds Django 2.0 and Wagtail 2.0 support

### LINKED ISSUE #22: Wagtail 2.0 support
This package can't be used with Wagtail 2.0.

## Current behavior

This package doesn't support Wagtail 2.0.

## Expected behavior

This package does support Wagtail 2.0.

## Steps to replicate behavior (include URLs)

Current code imports use, for example, `wagtail.wagtailcore` instead of the new `wagtail.core` ([example](https://github.com/cfpb/wagtail-sharing/blob/master/wagtailsharing/views.py#L7)). 

See Wagtail release notes about updating module paths [here](http://docs.wagtail.io/en/latest/releases/2.0.html#wagtail-module-path-updates), and an example pattern to follow [here](https://github.com/alexgleason/wagtailfontawesome/blob/739ad953dfdbfd61bba628f585bf4b4b2b4b6caf/wagtailfontawesome/wagtail_hooks.py#L5-L10).

### PR DESCRIPTION
**Pull request by chosak**
This change adds support for Django 2.0 and Wagtail 2.0 to this package. The README has been updated to reflect the change, and example import syntax has been changed to use Wagtail 2 imports.

Throughout the code, a try/except pattern has been used to support both Wagtail 2.x and legacy 1.x import styles.

Fixes #22.

## Checklist

* [X] Changes are limited to a single goal (no scope creep)
* [X] Code can be automatically merged (no conflicts)
* [X] New functions include new tests
* [X] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by Scotchester** [comment]
Hey Andy, if you wouldn't mind writing up some basic testing instructions, I'd be glad to help out. I can install this in my existing environment and make sure it doesn't break anything, but I've not installed Django 2.0 or Wagtail 2.0 anywhere yet.

**Comment by Scotchester** [comment]
I tested installing this locally against Django 1.8/Wagtail 1.13 and it still works.

**Comment by KyeRussell** [comment]
Any blockers on this?

**Comment by chosak** [comment]
@Scotchester here's a way to test this against Python 3.6, Wagtail 2.0, and Django 2.0:

1. Create a new isolated virtualenv with Python 3.6 named `testws`.

    ```sh
    $ mkvirtualenv --no-site-packages --python=python3.6 testws
    ```

2. Install this PR into the virtualenv. Pulls in Wagtail/Django 2. [This open issue](https://github.com/python-pillow/Pillow/issues/3068) also means that, at least for now on Macs, you need to override the version of Pillow that gets pulled by from those.

    ```sh
    $ pip install git+https://github.com/chosak/wagtail-sharing.git@wagtail-django-2
    $ pip install Pillow!=5.1.0
    ```

3. Create a new Wagtail project named `myproject`.

    ```sh
    $ wagtail start myproject
    $ cd myproject
    ```

4. Edit project settings to add wagtail-sharing apps.

    ```diff
    diff --git a/myproject/settings/base.py b/myproject/settings/base.py
    index fe5d391..6e2598f 100644
    --- a/myproject/settings/base.py
    +++ b/myproject/settings/base.py
    @@ -28,6 +28,7 @@ INSTALLED_APPS = [
         'search',

         'wagtail.contrib.forms',
    +    'wagtail.contrib.modeladmin',
         'wagtail.contrib.redirects',
         'wagtail.embeds',
         'wagtail.sites',
    @@ -48,6 +49,8 @@ INSTALLED_APPS = [
         'django.contrib.sessions',
         'django.contrib.messages',
         'django.contrib.staticfiles',
    +
    +    'wagtailsharing',
     ]

     MIDDLEWARE = [
    ```

5. Edit project URLs to add wagtail-sharing routing.

    ```diff
    diff --git a/myproject/urls.py b/myproject/urls.py
    index 4114338..1b3184c 100644
    --- a/myproject/urls.py
    +++ b/myproject/urls.py
    @@ -3,11 +3,13 @@ from django.conf.urls import include, url
     from django.contrib import admin

     from wagtail.admin import urls as wagtailadmin_urls
    -from wagtail.core import urls as wagtail_urls
     from wagtail.documents import urls as wagtaildocs_urls

    +from wagtailsharing import urls as wagtailsharing_urls
    +
     from search import views as search_views

    +
     urlpatterns = [
         url(r'^django-admin/', admin.site.urls),

    @@ -19,7 +21,7 @@ urlpatterns = [
         # For anything not caught by a more specific rule above, hand over to
         # Wagtail's page serving mechanism. This should be the last pattern in
         # the list:
    -    url(r'', include(wagtail_urls)),
    +    url(r'', include(wagtailsharing_urls)),

         # Alternatively, if you want Wagtail pages to be served from a subpath
         # of your site, rather than the site root:
    ```


6. To simulate accessing your site on a different hostname, you'll need to loosen [Django's default security settings](https://docs.djangoproject.com/en/2.0/ref/settings/#allowed-hosts) that only allow access on `localhost`. Create a new file `myproject/settings/local.py` with this content:

    ```py
    ALLOWED_HOSTS = ['*']
    ```

7. Create a database and a superuser.

    ```sh
    $ ./manage.py migrate
    $ ./manage.py createsuperuser
    ```

8. Run your local server.

    ```sh
    $ ./manage.py runserver
    ```

9. Login to the admin at http://localhost:8000/admin/ with the superuser you just created. Under Settings, Sharing Sites, add a new Sharing Site against the default Wagtail Site, with a custom subdomain on the same port, for example http://sharing.localhost:8000.

    image

    Hit Save to create the new Sharing Site.

10. To see wagtail-sharing in action, you'll want to compare what you see at http://localhost:8000 with what you see at http://sharing.localhost:8000. You should see the wagtail-sharing banner across the top of the page when visiting via the Sharing Site.
  
    image

    Unfortunately, whether you can hit this latter link in a browser or with curl depends somewhat on your local setup. For me Chrome tends to route localhost subdomains, but Safari or curl won't (they will if you add a line like `127.0.0.1 sharing.localhost` (temporarily) to your `/etc/hosts` file).

**Pull request merged**
