### PR TITLE
Wagtail 5.1 support

### PR DESCRIPTION
**Pull request by nickmoreton**
This updates the package to include any Wagtail v5.1 changes.

Upgrade docs [v5.0](https://docs.wagtail.org/en/stable/releases/5.0.html#upgrade-considerations) and [v5.1](https://docs.wagtail.org/en/stable/releases/5.1.html#upgrade-considerations-changes-affecting-all-projects)

## Additions

- Conditional usage of Snippets in place of ModelAdmin

## Changes

- Wagtail v5.0 and v5.1 to the test matrix

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by nickmoreton** [comment]
I'd also like to bring our own internal review of this work to your attention. https://github.com/torchbox-forks/wagtail-sharing/pull/2 as there has been some discussion around the correct usage of conditional version checks.

We'd like to use the `>=` throughout in place of `<=` and I wondered what your thoughts on this would be.

**Comment by nickmoreton** [comment]
Sometime ago this PR was submitted to you: https://github.com/cfpb/wagtail-sharing/pull/47 but it didn't get merged in. I've now reworked that in this branch: https://github.com/torchbox-forks/wagtail-sharing/pull/3
Would you be interested in considering it again now. Thanks

**Comment by chosak** [comment]
Hi @nickmoreton, thanks for this and apologies for the delay in reviewing.

Since 5.1 is the place where Wagtail deprecates modeladmin in favor of snippets, I thought it might make more sense to make a clear break there instead of introducing the complexity from trying to support both at once (as you've done well here). Therefore I've opened #70 which adds support for 5.0 only (still on modeladmin) and then #71 which supports 5.1 and 5.2 (using snippets) but drops support for 5.0. Once those get reviewed I'll plan to make two new wagtail-sharing releases for both those configurations.

Regarding #47, I've commented at https://github.com/cfpb/wagtail-sharing/pull/47#issuecomment-1819741547.

**Comment by chosak** [comment]
Support for Wagtail 5.1 and 5.2 was added in #71 and is included in [release 2.12](https://github.com/cfpb/wagtail-sharing/releases/tag/2.12).

**Pull request closed without merging**
